apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-1eqf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-1eqf
    app.kubernetes.io/part-of: tkrw-pr714-0075-0041-app
  name: devfile-sample-1eqf
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-1eqf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-1eqf
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0041-tenant/tkrw-pr714-0075-0041-app/devfile-sample-1eqf@sha256:1265ce1dc6d68dc736b2e87ac1a5aa6a8208f742cf4993e6eed9b26c1f526ba9
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
